config/routes.rb
Rails.application.routes.draw do
  get 'signups/new'
	root 'pages#home'

	get 'about' => 'pages#about'

	resources :signups

	get 'thanks' => 'signups#thanks'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/signup.rb
class Signup < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end

	def about
	end


end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  def new
  	@signup = Signup.new
  end

  def create
  	@signup = Signup.new(signup_params)
  		if @signup.save
  			redirect_to '/thanks'
  		else
  			flash[:error] = @signup.errors.full_messages
  			render 'new'
  		end
  end

  def thanks
  end

  private

  def signup_params
  	params.require(:signup).permit(:firstname, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photostories</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;500;700&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS link -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>

  <body>
    <%= render partial: "shared/sidebar_menu" %>

    <div id="page-content">
      <%= image_tag 'https://s3.amazonaws.com/codecademy-content/projects/z2d/stories/menu-white.svg', alt: "Open Menu", id: "menu-button"  %>
      <%= yield %>

      <%= render partial: "shared/footer" %>

    </div>

    <!-- Boostrap JS scripts -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<div class="header" id="about">
	<div class="container">
		<div class="content">
			<h1 class="white-text mx-auto">Relive your favorite memories</h1>
		</div>
	</div>
</div>
<section class="supporting">
	<div class="container">
		<h2>No more sorting through photos</h2>
		<p>Stories automatically finds your best photos and creates a new travelogue. This way you can capture and share your special moments in fresh new ways.</p>
		<%= link_to 'Sign up', new_signup_path, class: "btn btn-primary", role: "button" %>
	</div>
</section>

app/views/pages/home.html.erb
<main>
	<div class="header" id="home">
		<div class="container">
			<div class="row">
				<div class="content col-md-6 offset-md-6">
					<h1 class="white-text mx-auto">Photostories</h1>
					<h3 class="white-text mx-auto">Create and share your stories</h3>
					<%= link_to "Learn more", about_path, class: "btn btn-primary mx-auto", role: "button" %>
				</div>
			</div>
		</div>
	</div>
	<section class="supporting">
		<div class="container">
			<h2>Relive and share your adventures</h2>
			<p>Photostories automatically creates a digital journal filled with only your best photos.</p>
		</div>
	</section>
	<section class="secondary">
	</section>
	<section class="discover">
		<div class="container">
			<h2 class="content">Discover Photostories</h2>
			<%= link_to "Learn more", about_path, class: "btn btn-primary mx-auto", role: "button" %>
		</div>
	</section>
</main>

app/views/shared/_footer.html.erb
<footer>
	<div class="container bg-light">
		<p class="mx-auto">Made by Caitlin Quigley with help from Codecademy</p>
	</div>
</footer>

app/views/shared/_sidebar_menu.html.erb
<div id="menu">
	<ul id="menu-list">
		<li><%= link_to 'Home', root_path %></li>
		<li><%= link_to 'About', about_path %></li>
		<li><%= link_to 'Contact', new_signup_path %></li>
	</ul>
	<%= image_tag 'https://s3.amazonaws.com/codecademy-content/projects/z2d/stories/close-white.svg', alt: "Close Menu", id: "close-button"  %>
</div>

app/views/signups/new.html.erb
<div class="header" id="signup-new">
	<div class="container">
		<div class="content">
			<h1 class="white-text mx-auto">Get the latest updates from Photostories</h1>
			<%= form_with model: @signup, local: true, class: "signup-form col-md-6 offset-md-3" do |form| %>
				<div>
					<div class="form-group row">
						<%= form.label 'First Name ', class: "white-text" %>
						<%= form.text_field :firstname, class: "form-control" %>
					</div>
					<div class="form-group row">
						<%= form.label 'Email ', class: "white-text" %>
						<%= form.email_field :email, class: "form-control" %>
					</div>
					<div class="row">
						<%= form.submit "Join", class: "btn btn-light" %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/signups/thanks.html.erb
<div class="header" id="signup-new">
	<div class="container">
		<div class="content">
			<h1 class="white-text mx-auto">Thanks. We'll be in touch.</h1>
		</div>
	</div>
</div>